### ISSUE TITLE
XDG spec for config files

### ISSUE THREAD

**Issue by raffaem** [hugetim/nbstata#33]
The [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) specification states that config files should be located in `$XDG_CONFIG_HOME`, which should default to `$HOME/.config`.

Can we move `nbstata.conf` in e.g. `$XDG_CONFIG_HOME/nbstata/nbstata.conf`, while still reading from the old path (`$HOME/.nbstata.conf`) for backwards compatibility?

**Comment by hugetim** [comment]
I'm not familiar with Arch Linux or how it relates to other platforms. Is this XDG Base Directory spec universal?

I guess I'm also not clear on what you're requesting. A pull request would be the most direct way to show me. Otherwise, can you explain what we'd be doing different if we're "still reading from the old path"? How is that consistent with the request to "move `nbstata.conf`"?

**Comment by raffaem** [comment]
> I'm not familiar with Arch Linux or how it relates to other platforms. Is this XDG Base Directory spec universal?

Yes

https://en.wikipedia.org/wiki/Freedesktop.org#Base_Directory_Specification

> I guess I'm also not clear on what you're requesting.

move `~/.nbstata.conf` to `~/.config/nbstata/nbstata.conf`

> Otherwise, can you explain what we'd be doing different if we're "still reading from the old path"?

We would read from the new folder in addition to the old one, for backwards compatibility

> How is that consistent with the request to "move nbstata.conf"?

If `~/.config/nbstata/nbstata.conf` doesn't exist, you try the old `~/.nbstata.conf`.

The point is that people rely on this standard to administer their system, for example they backup `~/.config` instead of the entire home folder.

**Comment by huegerich** [comment]
Thank you, that clears it up for me.

I would have thought to move it to `~/.config/nbstata.conf`. Just to double check, you'd prefer putting it within a `nbstata` directory, right?

Also, when checking the XDG spec path, we should actually use the environment variable `$XDG_CONFIG_HOME/nbstata/nbstata.conf` rather than `$HOME/.config/nbstata/nbstata.conf`, right?

The current code is [here](https://github.com/hugetim/nbstata/blob/master/nbstata/config.py#L182) and [here](https://github.com/hugetim/nbstata/blob/master/nbstata/install.py#L100).

**Comment by raffaem** [comment]
> I would have thought to move it to ~/.config/nbstata.conf. Just to double check, you'd prefer putting it within a nbstata directory, right?

We may want other files in the future.

For example, a `~/.config/nbstata/nbstata.d` directory which contains user-defined STATA scripts to be run at startup. For instance to initialize the environment, or define variables or functions that the user frequently uses.

Or in the future we may want to support multiple STATA versions, so have a config file for each version.

Or the user may want to backup an old config file, keeping it in the same directory.

> Also, when checking the XDG spec path, we should actually use the environment variable $XDG_CONFIG_HOME/nbstata/nbstata.conf rather than $HOME/.config/nbstata/nbstata.conf, right?

We check if `XDG_CONFIG_HOME` is defined. If it isn't, we define `XDG_CONFIG_HOME=$HOME/.config`. Then we always use `$XDG_CONFIG_HOME/nbstata/nbstata.conf`.

**Comment by hugetim** [comment]
Ok, that sounds good. If you know of another Python project that handles a configuration file in a similar way (the simpler, the better), that would be helpful to see. Otherwise, I think this is enough to go on.

**Comment by raffaem** [comment]
https://github.com/pybliometrics-dev/pybliometrics/commit/b15ad45ee118682f522708811de275438a71587c

**Comment by hugetim** [comment]
Hmm, this code example does do anything with `XDG_CONFIG_HOME`, which is the part I was most looking for sample code for. But co-pilot or the like can probably help me with that, anyway.
